### PR TITLE
Add TWO import statements to the Scala Example

### PR DESCRIPTION
**Pull request by techmag**
Might be brain dead obvious to most but nice to provide out of the box compilability even if only a sample.

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @techmag,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by Mogztter** [comment]
> Might be brain dead obvious to most but nice to provide out of the box compilability even if only a sample.

Not at all, I'm feeling the same ! When a code sample didn't compile out of the box, it makes me angry :smile: 

Could you please sign the CLA and add this two lines for the Java sample as well ? Thanks!

**Comment by techmag** [comment]
As requested: (attached I hope!) 

Just want to say that I threw out all my pens (and even the printers!) well over a decade ago in preparation for the supposed paperless office wave :)  

In those immortal words of Scotty: How quaint...

Damn - no PDFs here... How am I supposed to get this document back to you please?

**Comment by Mogztter** [comment]
> How am I supposed to get this document back to you please?

You do not need to provide Typesafe the signed agreement but you do need to confirm with your GitHub account.
Once you've done that http://www.typesafe.com/contribute/cla/check/techmag should read "signed: true"

**Comment by techmag** [comment]
God you think I could actually read and follow instructions :) 

Done!

**Comment by Mogztter** [comment]
All good :smile: 
Could you add this two lines for the Java sample as well ?

Same lines with a semicolon:
```java
import java.io.File;
import org.apache.commons.mail.EmailAttachment;
```

Then I will merge your contribution, thanks!

**Comment by Mogztter** [comment]
Thanks :+1:

**Pull request merged**
