### PR TITLE
Upgrade to Play 2.5.0

### PR DESCRIPTION
**Pull request by marcospereira**
Also upgrades sample application and the following dependencies:

1. sbt-mima-plugin to version 0.1.8
2. interplay to version 1.1.1

### CODE REVIEW

**Comment by Mogztter** [comment]
Hey @marcospereira, thanks for your work. I'm not sure if we should upgrade to 2.5 now or just wait a final version...

**Comment by mkurz** [comment]
@Mogztter What about the `next` branch? Does it differ somehow from the master branch?

**Comment by marcospereira** [comment]
Hey @Mogztter, this is suppose to be a "early upgrade" to see if everything will work with the new version of Play Framework. I was not expecting a (final) release of play-mailer depending on a RC version of Play.

But instead, since I believe this module have a lot of users, this PR (and also a possible RC/snapshot release of play-mailer), will give those users the chance to test their applications and give us proper feedback.

WDYT?

**Comment by Mogztter** [comment]
@mkurz `next` branch is built against Play! master branch
@schmitch made some great changes and I think we should publish a `4.0.0` with Play 2.4.6. Currently there's only a "milestone" version.

Then we can merge your work and prepare the 5.x release :smile:

**Comment by marcospereira** [comment]
Play 2.5.0 was released:

https://groups.google.com/forum/#!topic/play-framework/aFEkSOaAEbk

This PR is already updated to reflect the final release.

**Comment by schmitch** [comment]
lgtm on sunday I will prolly add some documentation changes.

**Comment by Mogztter** [comment]
LGTM, thanks @marcospereira :+1:

**Comment by mkurz** [comment]
@Mogztter The `next` branch is not needed anymore now because of this PR. We should delete it.

**Comment by Mogztter** [comment]
@mkurz The `next` branch is built against Play! framework master branch (2.6 now), so we should update it (not delete it).

**Pull request merged**
