### PR TITLE
keep backwards compatibility

### PR DESCRIPTION
**Pull request by vmouta**
Keep backwards compatibility would be nice.

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @vmouta,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.typesafe.com/contribute/cla](http://www.typesafe.com/contribute/cla)

**Comment by Mogztter** [comment]
```
[error] /home/travis/build/playframework/play-mailer/src/main/scala/play/libs/mailer/MailerPlugin.java:3: cannot access play.Play
[error] bad class file: ZipFileIndexFileObject[/home/travis/.ivy2/cache/com.typesafe.play/play_2.11/jars/play_2.11-2.4.0-M3.jar(play/Play.class)]
[error] class file has wrong version 52.0, should be 50.0
[error] Please remove or make sure it appears in the correct subdirectory of the classpath.
[error] import play.Play;
[error]            ^
[error] (compile:compile) javac returned nonzero exit code
```
@jroper Can we build the play24 branch with the JDK7 ?

**Comment by Mogztter** [comment]
I didn't know about `play.Play.application().injector()` :smile:

**Comment by vmouta** [comment]
sorry if it isn't useful at all. No idea why did it fail since it works for me.

**Comment by Mogztter** [comment]
No not at all, I think it's a good idea to keep backwards compatibility with just two lines of code. I just want to make sure that @jroper is "feeling the same way".

**Comment by Mogztter** [comment]
> No idea why did it fail since it works for me.

We are building play-mailer with jdk6 and I think jdk7 is mandatory with Play2.4

**Comment by jroper** [comment]
Actually, Play 2.4 requires jdk8.

**Comment by jroper** [comment]
The switch to JDK8 is made in #32, once that's merged, you can close and reopen this pull request to force travis to rebuild.

**Comment by Mogztter** [comment]
@vmouta Build is OK, could you sign the CLA so we can proceed with your contribution ?

**Comment by vmouta** [comment]
long paper for such a small trivial thing :)... will do it.

**Comment by Mogztter** [comment]
yes but once this is done you can submit more pull requests :smile:

**Comment by jroper** [comment]
The build is still red because of a limitation of the validator, GitHub doesn't have an API for getting a users list of pull requests, so instead the validator loads the users recent activity, and looks for pull requests that have failed validation on them, in this case this PR had dropped out of that activity.  I can confirm that @vmouta has signed the CLA.

**Comment by Mogztter** [comment]
Thanks :+1:

**Pull request merged**
