### PR TITLE
Update to use Play 2.7.0

### LINKED ISSUE #158: Cross build for Scala 2.13.0
Just a reminder, should be done as soon as Play 2.7 is final, see https://github.com/playframework/playframework/pull/8998

https://github.com/playframework/play-mailer/blob/16f7763e1953e47ade58e9a8ba48048c59479d9d/build.sbt#L11

### PR DESCRIPTION
**Pull request by marcospereira**
Fixes #158.

### CODE REVIEW

**Comment by mkurz** [comment]
Please address #158 :smile:

**Comment by mkurz** [comment]
https://travis-ci.org/playframework/play-mailer/jobs/486762502#L1129-L1130

**Comment by mkurz** [comment]
```
[error] (*:update) sbt.ResolveException: unresolved dependency: com.typesafe.play#play-omnidoc_2.12;2.7.0: not found
```
:cry:

**Comment by mkurz** [comment]
@marcospereira I added some commits, I hope you don't mind. I disabled MiMa for now, it failed because there are no Scala 2.13 artifacts for the previous 6.0 release, which makes it fail.
We just need to enable MiMa again after we cut the 7.0 release.

**Comment by mkurz** [comment]
When the `play-omnidoc` release is out this should turn green.

**Comment by marcospereira** [comment]
Closing/opening to trigger a new build. :-)

**Pull request merged**
